### PR TITLE
Fix for OPTIONs method crash (#12)

### PR DESCRIPTION
**Pull request by pwaller**
This fixes issue #12.

### CODE REVIEW

**Comment by libwilliam** [comment]
It looks great. My only request before merging in the change is to remove the print at the end of the test method.

Thank you

**Comment by pwaller** [comment]
Ah yes, got spot. I've forced an update.

**Comment by libwilliam** [comment]
Thank you for your help on this!

**Comment by libwilliam** [comment]
I forgot to mention, I will put a bug fix release out soon (hopefully today).

**Comment by pwaller** [comment]
Thanks for being quick! :dart:

**Comment by libwilliam** [comment]
The change is now live on PyPI.

**Pull request merged**
