### PR TITLE
Optionally cache gzipped responses.

### PR DESCRIPTION
**Pull request by jmcarp**
If gzipped assets don't change often, we can save a lot of work by caching the compressed responses. The typical usage would be a cache keyed on some hash of the original content:

```python
app['COMPRESS_CACHE_KEY'] = lambda response: hashlib.sha1(response.get_data()).hexdigest()
```

I implemented a simple `DictCache`, but it would be straightforward to add disk, Redis, etc. if necessary (although not worthwhile for my use case). If this patch is of interest, I'll add tests and add whatever cleanup is recommended.

### CODE REVIEW

**Comment by libwilliam** [comment]
I wanted to let you know I haven't had much time to look at this yet but it sounds great. I'll look into it deeper in the next couple days and get back you.

**Comment by libwilliam** [comment]
Sorry it took so long for me to merge this in. It looks great! Thank you.

**Comment by bookernath** [comment]
What's the best way to use this in tandem with flask-cache?

**Comment by jkomusin** [comment]
@bookernath I'm a little late, but for anyone else looking for this, here's a snippet that seems to sync them up well for me:

```
from flask_cache import Cache
from flask_compress import Compress

cache = Cache(app, config=app.config.get('FLASK_CACHE'))
# Tell flask-compress about our Flask-Cache instance so it can use it as a backend
app.config['COMPRESS_CACHE_BACKEND'] = lambda: cache
Compress(app)
```

**Comment by bookernath** [comment]
@jkomusin thanks for getting back to me!

I should have been more explicit though - ideally I'd want to make sure that Flask is caching the compressed response, since it'll take up less space in the cache. My best read on what you've proposed here is that the uncompressed response will be stored in cache and then compressed when read from cache. Do I have that right?

**Comment by jkomusin** [comment]
Ah I think I see what you're saying. I'm not caching the uncompressed responses from any of my Flask views right now, just checking to see if there's a matching SHA1 compressed result in the cache.

I suspect you're correct though. The method I posted, if you simply decorated a Flask view, the uncompressed response would be cached and then the compressed response would also be cached. The view would return the cached uncompressed response, then the flask-compress after_request hook would pull the cached compressed response.

**Pull request merged**
